// regular icons
export { default as BellIcon } from './bell.svg'
export { default as EyeIcon } from './eye.svg'
export { default as UserProfilePictureIcon } from './profile-picture.svg'
export { default as BarChartIcon } from './bx-bar-chart.svg'
export { default as BitcoinIcon } from './bx-bitcoin.svg'
export { default as CheckShieldIcon } from './bx-check-shield.svg'
export { default as ChevronDownIcon } from './bx-chevron-down.svg'
export { default as CloseIcon } from './x.svg';
export { default as CloseCircleIcon } from './x-circle.svg';
export { default as ChevronUpcon } from './bx-chevron-up.svg'
export { default as ChevronLeftIcon } from './bx-chevron-left.svg'
export { default as ChevronRightIcon } from './bx-chevron-right.svg'
export { default as ChevronsLeftIcon } from './bx-chevrons-left.svg'
export { default as ChevronsRightIcon } from './bx-chevrons-right.svg'
export { default as CloudUpload2Icon } from './bx-cloud-upload.svg'
export { default as CloudUploadIcon } from './cloud-upload.svg'
export { default as CodeIcon } from './bx-code.svg'
export { default as DotsVerticalIcon } from './bx-dots-vertical-rounded.svg'
export { default as DotsHorizontalIcon } from './bx-dots-horizontal-rounded.svg'
export { default as GridSmallIcon } from './bx-grid-small.svg'
export { default as HeartIcon } from './bx-heart.svg'
export { default as IdCardIcon } from './bx-id-card.svg'
export { default as LayerIcon } from './bx-layer.svg'
export { default as LineChartIcon } from './bx-line-chart.svg'
export { default as LinkIcon } from './bx-link.svg'
export { default as LinkAltIcon } from './bx-link-alt.svg'
export { default as MenuIcon } from './bx-menu.svg'
export { default as MicrophoneIcon } from './bx-microphone.svg'
export { default as PencilIcon } from './bx-pencil.svg'
export { default as PurchaseTagAltIcon } from './bx-purchase-tag-alt.svg'
export { default as RefreshIcon } from './bx-refresh.svg'
export { default as SearchIcon } from './bx-search.svg'
export { default as ShareAltIcon } from './bx-share-alt.svg'
export { default as ShowIcon } from './bx-show.svg'
export { default as TagIcon } from './bx-tag.svg'
export { default as TransferIcon } from './bx-transfer.svg'
export { default as TrophyIcon } from './bx-trophy.svg'
export { default as UserIcon } from './bx-user.svg'
export { default as WalletAltIcon } from './bx-wallet-alt.svg'
export { default as CopyToClipboardIcon } from './content_copy_black_24dp.svg'
export { default as BackspaceIcon } from './backspace_black_24dp.svg'
export { default as ArrowBackIcon } from './arrow_back_black_24dp.svg'
export { default as ArrowForwarIcon } from './arrow_forward_black_24dp.svg'
export { default as AddIcon } from './add_black_24dp.svg'
export { default as HelpIcon } from './help_black_24dp.svg'
export { default as HelpOutlineIcon } from './help_outline_black_24dp.svg'
export { default as SwapHorIcon } from './swap_horiz_black_24dp.svg'
export { default as SwapVerIcon } from './swap_vert_black_24dp.svg'
export { default as WifiIcon } from './wifi.svg'

// logo icons
export { default as DiscordIcon } from './bxl-discord.svg'
export { default as FacebookIcon } from './bxl-facebook-circle.svg'
export { default as PinterestAltIcon } from './bxl-pinterest-alt.svg'
export { default as PinterestIcon } from './bxl-pinterest.svg'
export { default as RedditIcon } from './bxl-reddit.svg'
export { default as TelegramIcon } from './bxl-telegram.svg'
export { default as TwitterIcon } from './bxl-twitter.svg'
export { default as YouTubeIcon } from './YouTube_icon.svg'
export { default as InstagramIcon } from './bxl-instagram.svg'

// solid icons
export { default as CalendarIconSolid } from './bxs-calendar.svg'
export { default as CalendarAltIconSolid } from './bxs-calendar-alt.svg'
export { default as CheckShieldIconSolid } from './bxs-check-shield.svg'
export { default as EVStationIconSolid } from './bxs-ev-station.svg'
export { default as FilterAltIconSolid } from './bxs-filter-alt.svg'
export { default as FlagAltIconSolid } from './bxs-flag-alt.svg'
export { default as GasPumpIconSolid } from './bxs-gas-pump.svg'
export { default as HeartIconSolid } from './bxs-heart.svg'
export { default as HomeIconSolid } from './bxs-home.svg'
export { default as HotIconSolid } from './bxs-hot.svg'
export { default as ImageIconSolid } from './bxs-image-alt.svg'
export { default as ImagesIconSolid } from './bxs-image.svg'
export { default as KeyIconSolid } from './bxs-key.svg'
export { default as LayerIconSolid } from './bxs-layer.svg'
export { default as LockIconSolid } from './bxs-lock.svg'
export { default as MessageRoundedIconSolid } from './bxs-message-rounded.svg'
export { default as MesssageIconSolid } from './bxs-message.svg'
export { default as MicrophoneOffIconSolid } from './bxs-microphone-off.svg'
export { default as MicrophoneIconSolid } from './bxs-microphone.svg'
export { default as MoonIconSolid } from './bxs-moon.svg'
export { default as PencilIconSolid } from './bxs-pencil.svg'
export { default as PinIconSolid } from './bxs-pin.svg'
export { default as PurchaseTagAltIconSolid } from './bxs-purchase-tag-alt.svg'
export { default as SendIconSolid } from './bxs-send.svg'
export { default as SunIconSolid } from './bxs-sun.svg'
export { default as TagIconSolid } from './bxs-tag.svg'
export { default as UserIconSolid } from './bxs-user-circle.svg'
export { default as WalletAltIconSolid } from './bxs-wallet-alt.svg'
export { default as WalletIconSolid } from './bxs-wallet.svg'

export { default as CheckIcon } from './check.svg'
export { default as CheckCircleIcon } from './check-circle.svg'
export { default as CheckRoundedIcon } from './check-rounded.svg'
export { default as CheckCircleRoundedIcon } from './check-circle-rounded.svg'

export { default as VisibilityIcon } from './visibility-on.svg';
export { default as VisibilityOffIcon } from './visibility-off.svg';

/* outline */
export { default as FilterIcon } from './heroicon-filter.svg'

export { default as EthereumIcon } from './tokens/ethereum-eth.svg'

